### ISSUE TITLE
anpassung mailadresse

### ISSUE THREAD

**Issue by jwaibel** [HeikoBornholdt/uberspace-icinga#3]
Erstmal danke für die ausführliche Anleitung. 

Eine Ergänzung hätte ich noch:

In den Dateien /home/$USER/opt/icinga/etc/objects/contacts.cfg und /home/$USER/opt/icinga/etc/icinga.cfg  sollte die Mailadresse angepasst werden. Dort steht nach der Installation <username>@localhost. Das ührt dazu das statusmails an <username>@localhost.uberspace.de geschickt werden und als unzustellbar verworfen werden. 

---

Return-Path: XXXXX@musca.uberspace.de
Received: (qmail 1982 invoked by uid 878); 10 Jul 2013 12:03:25 -0000
Message-ID: 20130710120325.1981.qmail@musca.uberspace.de
From: XXXXX@musca.uberspace.de
Date: Wed, 10 Jul 2013 14:03:25 +0200
## To: XXXXX@localhost.uberspace.de

Die letzte Zeile zeigt den Fehler.

Jürgen

**Comment by HeikoBornholdt** [comment]
Hallo Jürgen,

da hast du natürlich Recht.
Jedoch geht die Anleitung ja allgemein nur auf die Installation und nicht auf die Konfiguration ein.
Konsequenterweise müsste man dann mehr auf die Konfiguration eingehen. Doch das wird ja bereits hinreichend in der offiziellen Dokumentation erläutert. Oder gibt es bei der Konfiguration auf einen Uberspace Besonderheiten? Mir fallen da gerade Keine ein, ist aber auch schon etwas her bei mir.

Gruß,
Heiko
